# Generated by Django 4.2.4 on 2023-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_on"], "verbose_name": "Note", "verbose_name_plural": "Notes"},
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["-created_on", "user"], name="notes_note_created_a57589_idx"),
        ),
    ]
