# Generated by Django 4.2.4 on 2023-10-03 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_note_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="updated_on",
        ),
    ]
