# Generated by Django 4.2.4 on 2023-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_remove_note_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
    ]
